### ISSUE TITLE
Use concaveman!

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-concave#11]
@mourner made [concaveman](https://github.com/mapbox/concaveman) - let's use it!

**Comment by mourner** [comment]
I'd be happy to see it used here, as it's orders of magnitude faster. It should be noted though that there are disadvantages too:

- there are two tuning parameters (`concavity` and `lengthThreshold`) that are both not very intuitive, so we would have to make the API less straightforward or settle on some defaults
- the output may be less "optimal" because it's not based on Delaunay triangulation, although I'm not sure — needs some comparisons

**Comment by kelvinabrokwa** [comment]
@mourner @morganherlocker it looks like concaveman doesn't behave in the same way that the current implementation does. For example, it never creates islands (multipolygons) whereas turf-concave, under certain conditions, will.

@morganherlocker also tells me this is not a thing in turf :arrow_down: 

![](https://cloud.githubusercontent.com/assets/7795202/13364337/417682d8-dc9c-11e5-90fe-fc7a1bc0ce01.png)

**Comment by tmcw** [comment]
Implemented in https://github.com/Turfjs/turf
